name: Deploy Next js Gtihub Profile Viewer App
# in the on we define the trigger which will make the github actions to execute
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # pre build action to copy your code from repo to the runner i.e. github provided VM

      - name: Step Up Node
        uses: actions/setup-node@v4 # Pre build action to install and setup node in the runner
        with:
          node-version: "20"

      # Login to Github Container Repository
      - name: Login to GHCR
        uses: docker/login-action@v3 # pre-built action plugin for docker login
        with:
          registry: ghcr.io # The Registry we are logging into (Github's)
          username: ${{ github.actor }} # Your Github Username (auto-filled by Github)
          password: ${{ secrets.GITHUB_TOKEN }}
          # Auto Generated secret token, provided by Github automatically
          # No need to create this yourself - it exist for every repo/workflow

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # The action configures the Buildx properly to support multi platform builds
      # Step : Build Docker image from DockerFile then put it to GHCR
      - name: Build and Push Image
        uses: docker/build-push-action@v5 # pre-built action for build+push
        with:
          context: . # build using files in current directory (Where DockerFile is)
          push: true # after building, push image to registry (not just build locally)
          platforms: linux/amd64,linux/arm64 # to make the Image multi platform and suitable for the pi 
          tags: ghcr.io/${{ github.repository }}:latest
          # names/tags the imgage, e.g. ghcr.io/yourusername/yourrepo:latest
          # "latest" = tag name , means "most recent version"
      


          # Step : SSH into Raspberry PI and update the running app
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1 # pre-build action that handles SSH Connection 
        with:
          host: ${{ secrets.PI_HOST }} # Pi's address (hostname/IP), stored securely
          username: ${{ secrets.PI_USER }} # Pi's SSH username , stored securely
          key: ${{ secrets.PI_SSH_KEY }} # private key for passowrdless login, stored securely
          scritps: | # "|" means multi line block - these are the command that will run on the PI once connected
            cd /home/corvus82
            docker compose pull
            docker compose up -d

